// Ordre identique au quiz JetPunk "Drapeaux du Monde" : [nom, code ISO (fichier flags/xx.svg), alias séparés par |]
const RAW = [
  ["États-Unis", "us", "USA|US|Amérique|United States|États-Unis d'Amérique"],
  ["Royaume-Uni", "gb", "UK|GB|Grande-Bretagne|Angleterre|United Kingdom|Great Britain"],
  ["Australie", "au", "Australia"],
  ["Nouvelle-Zélande", "nz", "New Zealand|NZ"],
  ["Canada", "ca", ""],
  ["Russie", "ru", "Fédération de Russie|Russia"],
  ["Pays-Bas", "nl", "Hollande|Netherlands|Holland"],
  ["France", "fr", ""],
  ["Italie", "it", "Italy"],
  ["Irlande", "ie", "Ireland|Eire|Éire"],
  ["Côte d'Ivoire", "ci", "Ivory Coast|Cote divoire|Cote d ivoire"],
  ["Bulgarie", "bg", "Bulgaria"],
  ["Hongrie", "hu", "Hungary"],
  ["Madagascar", "mg", ""],
  ["Japon", "jp", "Japan"],
  ["Corée du Sud", "kr", "South Korea|Corée Sud|Sud Corée|République de Corée"],
  ["Bangladesh", "bd", "Bengladesh"],
  ["Palaos", "pw", "Palau|Belau"],
  ["Brésil", "br", "Brazil"],
  ["Suède", "se", "Sweden"],
  ["Finlande", "fi", "Finland"],
  ["Norvège", "no", "Norway"],
  ["Islande", "is", "Iceland"],
  ["Danemark", "dk", "Denmark"],
  ["Grèce", "gr", "Greece"],
  ["Géorgie", "ge", "Georgia"],
  ["Tonga", "to", ""],
  ["Malte", "mt", "Malta"],
  ["République Dominicaine", "do", "Dominicaine|Rép Dominicaine|Rép Dom|Republique Dom|Dominican Republic"],
  ["Chine", "cn", "China|RPC"],
  ["Viêt Nam", "vn", "Vietnam|Viet Nam"],
  ["Cameroun", "cm", "Cameroon"],
  ["Burkina Faso", "bf", "Burkina"],
  ["Birmanie", "mm", "Myanmar|Burma"],
  ["Kosovo", "xk", ""],
  ["Albanie", "al", "Albania"],
  ["Chypre", "cy", "Cyprus"],
  ["Bhoutan", "bt", "Bhutan"],
  ["Liban", "lb", "Lebanon"],
  ["Népal", "np", "Nepal"],
  ["Vatican", "va", "Cité du Vatican|État du Vatican|Saint-Siège|Vatican City|Holy See"],
  ["Suisse", "ch", "Switzerland"],
  ["Belgique", "be", "Belgium"],
  ["Niger", "ne", ""],
  ["Gabon", "ga", ""],
  ["Israël", "il", "Israel"],
  ["Papouasie-Nouvelle-Guinée", "pg", "Papouasie|PNG|Papua New Guinea|Nouvelle Guinée"],
  ["Saint-Marin", "sm", "San Marino|Saint Marino"],
  ["République Démocratique du Congo", "cd", "RDC|RD Congo|RDCongo|Congo Kinshasa|Congo Démocratique|Congo RDC|Zaïre|DRC|DR Congo|Democratic Republic of the Congo"],
  ["Turquie", "tr", "Turkey|Türkiye"],
  ["Tunisie", "tn", "Tunisia"],
  ["Algérie", "dz", "Algeria"],
  ["Pakistan", "pk", ""],
  ["Mauritanie", "mr", "Mauritania"],
  ["Azerbaïdjan", "az", "Azerbaijan"],
  ["Comores", "km", "Comoros"],
  ["Libye", "ly", "Libya"],
  ["Malaisie", "my", "Malaysia"],
  ["Ouzbékistan", "uz", "Uzbekistan"],
  ["Singapour", "sg", "Singapore"],
  ["Turkménistan", "tm", "Turkmenistan"],
  ["Maldives", "mv", ""],
  ["Oman", "om", ""],
  ["Arabie Saoudite", "sa", "Arabie|Saudi Arabia"],
  ["Allemagne", "de", "Germany|Deutschland"],
  ["Espagne", "es", "Spain"],
  ["Afrique du Sud", "za", "South Africa|Afrique Sud|RSA"],
  ["Soudan du Sud", "ss", "South Sudan|Soudan Sud|Sud Soudan"],
  ["Jamaïque", "jm", "Jamaica"],
  ["Mexique", "mx", "Mexico"],
  ["Inde", "in", "India"],
  ["Eswatini", "sz", "Swaziland"],
  ["Kenya", "ke", ""],
  ["Barbade", "bb", "Barbados"],
  ["Autriche", "at", "Austria"],
  ["Pologne", "pl", "Poland"],
  ["Indonésie", "id", "Indonesia"],
  ["Monaco", "mc", ""],
  ["Pérou", "pe", "Peru"],
  ["Yémen", "ye", "Yemen"],
  ["Égypte", "eg", "Egypt"],
  ["Irak", "iq", "Iraq"],
  ["Syrie", "sy", "Syria"],
  ["Émirats Arabes Unis", "ae", "EAU|UAE|Émirats|Émirats Arabes|United Arab Emirates"],
  ["Jordanie", "jo", "Jordan"],
  ["Koweït", "kw", "Kuwait"],
  ["Soudan", "sd", "Sudan"],
  ["Tadjikistan", "tj", "Tajikistan"],
  ["Iran", "ir", ""],
  ["Malawi", "mw", ""],
  ["Antigua-et-Barbuda", "ag", "Antigua|Antigua Barbuda|Antigua and Barbuda"],
  ["Argentine", "ar", "Argentina"],
  ["Uruguay", "uy", ""],
  ["Rwanda", "rw", ""],
  ["Macédoine du Nord", "mk", "Macédoine|North Macedonia|Macedonia"],
  ["Îles Marshall", "mh", "Marshall|Marshall Islands"],
  ["Philippines", "ph", ""],
  ["Kiribati", "ki", ""],
  ["Kazakhstan", "kz", "Kazakstan"],
  ["Namibie", "na", "Namibia"],
  ["Nauru", "nr", ""],
  ["Venezuela", "ve", ""],
  ["Seychelles", "sc", ""],
  ["République du Congo", "cg", "Congo|Congo Brazzaville|Rép du Congo|Congo République|Republic of the Congo"],
  ["Tanzanie", "tz", "Tanzania"],
  ["Saint-Christophe-et-Niévès", "kn", "Saint Kitts|Saint-Kitts-et-Nevis|Saint Kitts et Nevis|St Kitts|Saint Christophe|Kitts et Nevis|Saint Kitts and Nevis"],
  ["Trinité-et-Tobago", "tt", "Trinidad|Trinidad et Tobago|Trinité|Trinidad and Tobago"],
  ["Brunei", "bn", "Brunei Darussalam"],
  ["Bosnie-Herzégovine", "ba", "Bosnie|Bosnie Herzegovine|Bosnia|Bosnia and Herzegovina"],
  ["Bahamas", "bs", ""],
  ["Érythrée", "er", "Eritrea"],
  ["Timor Oriental", "tl", "Timor-Leste|Timor|East Timor"],
  ["Zimbabwe", "zw", ""],
  ["Sao Tomé-et-Principe", "st", "Sao Tomé|Sao Tome|São Tomé|Sao Tome and Principe"],
  ["Guyana", "gy", ""],
  ["Mozambique", "mz", ""],
  ["Vanuatu", "vu", ""],
  ["Djibouti", "dj", ""],
  ["Guinée Équatoriale", "gq", "Équato-Guinée|Equatorial Guinea|Guinée Equatoriale"],
  ["République Tchèque", "cz", "Tchéquie|Tchèque|Rép Tchèque|Czech Republic|Czechia"],
  ["Cuba", "cu", ""],
  ["Panama", "pa", ""],
  ["Chili", "cl", "Chile"],
  ["Liberia", "lr", "Libéria"],
  ["Taïwan", "tw", "Taiwan|Formose|République de Chine"],
  ["Samoa", "ws", ""],
  ["Corée du Nord", "kp", "North Korea|Corée Nord|Nord Corée|RPDC"],
  ["Laos", "la", ""],
  ["Cap-Vert", "cv", "Cabo Verde|Cap Vert|Cape Verde"],
  ["Belize", "bz", ""],
  ["Haïti", "ht", "Haiti"],
  ["Cambodge", "kh", "Cambodia"],
  ["Liechtenstein", "li", ""],
  ["Paraguay", "py", ""],
  ["Serbie", "rs", "Serbia"],
  ["Slovaquie", "sk", "Slovakia"],
  ["Croatie", "hr", "Croatia"],
  ["Slovénie", "si", "Slovenia"],
  ["Costa Rica", "cr", ""],
  ["Thaïlande", "th", "Thailand"],
  ["Luxembourg", "lu", ""],
  ["Honduras", "hn", ""],
  ["États Fédérés de Micronésie", "fm", "Micronésie|Micronesia|États Fédérés|FSM"],
  ["Somalie", "so", "Somalia"],
  ["Salvador", "sv", "El Salvador"],
  ["Nicaragua", "ni", ""],
  ["Estonie", "ee", "Estonia"],
  ["Botswana", "bw", ""],
  ["Sierra Leone", "sl", "Sierra Leon"],
  ["Angola", "ao", ""],
  ["Afghanistan", "af", ""],
  ["Burundi", "bi", ""],
  ["Biélorussie", "by", "Bélarus|Belarus"],
  ["Bahreïn", "bh", "Bahrain"],
  ["Guinée", "gn", "Guinée Conakry|Conakry|Guinea"],
  ["Mali", "ml", ""],
  ["Sénégal", "sn", "Senegal"],
  ["Bénin", "bj", "Benin"],
  ["Togo", "tg", ""],
  ["Guinée-Bissau", "gw", "Guinée Bissau|Bissau|Guinea Bissau|Guinée Bisau"],
  ["Éthiopie", "et", "Ethiopia"],
  ["Lituanie", "lt", "Lithuania"],
  ["Bolivie", "bo", "Bolivia"],
  ["Ghana", "gh", ""],
  ["Suriname", "sr", "Surinam"],
  ["Dominique", "dm", "Dominica"],
  ["Grenade", "gd", "Grenada"],
  ["Maurice", "mu", "Île Maurice|Mauritius"],
  ["Arménie", "am", "Armenia"],
  ["Roumanie", "ro", "Romania"],
  ["Tchad", "td", "Chad"],
  ["Colombie", "co", "Colombia"],
  ["Équateur", "ec", "Ecuador"],
  ["Moldavie", "md", "Moldova|Moldovie"],
  ["Andorre", "ad", "Andorra"],
  ["Portugal", "pt", ""],
  ["Maroc", "ma", "Morocco"],
  ["Kirghizistan", "kg", "Kirghizstan|Kirghizie|Kyrgyzstan"],
  ["Ouganda", "ug", "Uganda"],
  ["Sri Lanka", "lk", "Ceylan"],
  ["Mongolie", "mn", "Mongolia"],
  ["Monténégro", "me", "Montenegro"],
  ["Nigeria", "ng", "Nigéria"],
  ["Salomon", "sb", "Îles Salomon|Solomon Islands|Solomon"],
  ["Lesotho", "ls", ""],
  ["Saint-Vincent-et-les-Grenadines", "vc", "Saint Vincent|St Vincent|Grenadines|Saint Vincent and the Grenadines"],
  ["Guatemala", "gt", ""],
  ["Ukraine", "ua", ""],
  ["Zambie", "zm", "Zambia"],
  ["Lettonie", "lv", "Latvia"],
  ["Qatar", "qa", "Katar"],
  ["Fidji", "fj", "Fiji|Fiji Islands|Îles Fidji"],
  ["Tuvalu", "tv", ""],
  ["Sainte-Lucie", "lc", "Saint Lucie|Saint Lucia|St Lucia|Sainte Lucie"],
  ["République Centrafricaine", "cf", "Centrafrique|RCA|Centrafricaine|Rép Centrafricaine|Central African Republic"],
  ["Gambie", "gm", "Gambia"],
];

// Cas où le quiz utilise un autre drapeau que la bibliothèque standard (Afghanistan : drapeau actuel des talibans)
const FILE = { af: "af.webp" };

export const COUNTRIES = RAW.map(([name, iso, aliases]) => ({
  name,
  iso,
  file: FILE[iso] ?? `${iso}.svg`,
  aliases: aliases ? aliases.split("|") : [],
}));
